### ISSUE TITLE
considered MIT license?

### ISSUE THREAD

**Issue by bburdette** [klingtnet/rsoundio#2]
Just curious why gpl3 vs MIT.  libsoundio uses MIT so seems like that would be a good fit here.

**Comment by klingtnet** [comment]
The reason is, that the GPL enforces that modifications to the source code have to be open sourced as well. Maybe I'm changing the license to MIT in a future release, but not before 1.0.
If you have any concerns about the usage of the GPL license, then please let me know.

**Comment by bburdette** [comment]
You might consider the [LGPL](http://copyleft.org/guide/comprehensive-gpl-guidech11.html#x14-10100010.5), which, as I understand it, would allow static linkage with proprietary programs while still forcing modifications to rsoundio to be made public.  

Personally its not a problem for me right now as I'm currently working on open source code.  It would be nice to standardize on one library for proprietary and non-proprietary though.  

Anyway, nice work on the library, very clean!  It works on arm, I was testing a number of libs this weekend and this is one that works on the raspberry pi (arch).  libsoundio isn't in the arch repos yet but it builds successfully if you disable jack support.  That should be fixed soon according to a bug report I found.

**Comment by klingtnet** [comment]
@bburdette 

I'm happy that you like it! I've already made a bug report for the JACK fix in Arch Linux. The issue closed and will be fixed with next JACK release in the Arch repositores (the version from the `community-testing` repos works fine). Also very good to hear that it works on Arch! I'm building a FM synth in Rust that I want to test on a raspberry Pi 3 as well.

**PS**: I will consider to choose an LGPL license but not now.
**PPS**: If you like to contribute to `rsoundio` then please send me PRs or open issues etc.

**Comment by MrMormon** [comment]
Especially since rsoundio only really supports the Linux portions of libsoundio right now, rsoundio could really use contributors. But allowing contributors would make changing the license more difficult. Which is your priority?

**Comment by klingtnet** [comment]
> Especially since rsoundio only really supports the Linux portions of libsoundio right now, rsoundio could really use contributors.

I haven't tested it on Windows or Mac yet but I think that the Rust part is not using any platform specific code.

Contributors are welcome and I would be happy to get PRs. Are there any concerns with the current dual Apache/MIT license?

**Comment by MrMormon** [comment]
Whoops, really sorry about missing the license change!
