### ISSUE TITLE
rsoundio is broken with rustc 1.11.0

### ISSUE THREAD

**Issue by klingtnet** [klingtnet/rsoundio#8]
rsoundio's audio output, or at least the JACK backend, is broken when I try use it with rustc 1.11.0.
Surprisingly, it compiles without an error but it always uses `ALSA` as backend and explicit backend selection crashes.

**Comment by klingtnet** [comment]
A workaround is to compile with `rustc 1.10.0`. You can use the following commands to install `1.10.0` assuming your are using `rustup`:

```sh
$ rustup toolchain install '1.10.0'
$ rustup run 1.10.0 -- cargo run --release --example sine
```

**Comment by omgbebebe** [comment]
It caused by that fact, that the rsoundio builds own copy of the libsoundio library, but with disabled `jack` and `pulseaudio` support (https://github.com/klingtnet/rsoundio/blob/master/build.rs#L121-L122). And when `cargo run` is executed it injects `LD_PRELOAD_PATH` which points to the builded `libsoundio.so`. When I directly run builded binary from `target/{debug,release}/` directory it uses system library and works as expected.
I'm a very new with cargo and rust and I can't figure out why switching to the version `1.11.0` helps.

**Comment by klingtnet** [comment]
Nice catch, also, `build.rs` should not build libsoundio if it is already available on the system ([build.rs](https://github.com/klingtnet/rsoundio/blob/master/build.rs#L49-L56)) but the redundant `else` branch will build it unconditionally.

**Comment by klingtnet** [comment]
Okay, it seems to be safe to remove [lines 52-54, `build.rs`](https://github.com/klingtnet/rsoundio/blob/master/build.rs#L52-L54) so the system's libsoundio is used.
